version: '3'
services:
  app:
    build: .
    ports:
      - '10000:10000'
    depends_on:
      - mongo
    environment:
      - PORT=10000

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
volumes:
  docker-test:
