version: '3'
services:
  app:
    build: .
    ports:
      - '10000:10000'
    depends_on:
      - mongo
    environment:
      - IP=localhost
      - PORT=10000

  mongo:
    image: mongo
    ports:
      - '27017:27017'
